version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:${DB_PORT}
    expose:
      - ${DB_PORT}
    volumes:
      - ./tests/sql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - my-db:/var/lib/mysql
  golang-rump-up:
    container_name: golang-rump-up
    links:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:${API_PORT}
    expose:
      - ${API_PORT}
volumes:
  my-db:
